extends SceneTree

const Layout := preload("res://desktop_layout.gd")

func _init() -> void:
	assert(Layout.window_height("") == 160)
	assert(Layout.window_height("settings") == 388)
	assert(Layout.window_height("inspect") == 438)
	var usable := Rect2i(20, 30, 1920, 1040)
	var compact_position := Layout.bottom_anchored_position(usable, Layout.window_height(""))
	var expanded_position := Layout.bottom_anchored_position(usable, Layout.window_height("inspect"))
	assert(compact_position.y + Layout.window_height("") == expanded_position.y + Layout.window_height("inspect"))
	assert(compact_position == Vector2i(20, 910))
	assert(expanded_position == Vector2i(20, 632))
	var inspect := Layout.overlay_rect(1280.0, "inspect")
	var strip_top := Layout.strip_top("inspect")
	assert(inspect.end.y <= strip_top)
	assert(inspect.position.x >= 8.0)
	var control := Layout.control_rect(1280.0, "inspect", 274.0)
	assert(control.position.y >= strip_top and control.end.y <= strip_top + Layout.STRIP_HEIGHT)
	assert(Layout.window_height("") == Layout.STRIP_HEIGHT)
	var polygon := Layout.passthrough_polygon(1280.0, "inspect", 274.0)
	assert(polygon.size() == 6, "overlay and shelf must use a concave L hit outline")
	print("Desktop layout tests passed")
	quit(0)
