extends SceneTree

const Layout := preload("res://desktop_layout.gd")

func _init() -> void:
	assert(Layout.window_height("") == 160)
	assert(Layout.window_height("settings") == 388)
	assert(Layout.window_height("inspect") == 438)
	assert(Layout.window_height("debug") == 438)
	var usable := Rect2i(20, 30, 1920, 1040)
	var compact_position := Layout.bottom_anchored_position(usable, Layout.window_height(""))
	var settings_position := Layout.bottom_anchored_position(usable, Layout.window_height("settings"))
	var expanded_position := Layout.bottom_anchored_position(usable, Layout.window_height("inspect"))
	assert(compact_position.y + Layout.window_height("") == usable.end.y)
	assert(settings_position.y + Layout.window_height("settings") == usable.end.y)
	assert(expanded_position.y + Layout.window_height("inspect") == usable.end.y)
	assert(compact_position.y + Layout.window_height("") == expanded_position.y + Layout.window_height("inspect"))
	assert(compact_position == Vector2i(20, 910))
	assert(expanded_position == Vector2i(20, 632))
	var inspect := Layout.overlay_rect(1280.0, "inspect")
	var strip_top := Layout.strip_top("inspect")
	assert(inspect.end.y <= strip_top)
	assert(inspect.end.y == strip_top)
	assert(inspect.position.x >= 8.0)
	var control := Layout.control_rect(1280.0, "inspect", 274.0)
	assert(control.position.y >= strip_top and control.end.y <= strip_top + Layout.STRIP_HEIGHT)
	var compact_strip := Layout.strip_rect(1280.0, "")
	assert(compact_strip.position.y == 0.0 and compact_strip.size.y == Layout.STRIP_HEIGHT)
	assert(Layout.window_height("") == Layout.STRIP_HEIGHT, "compact height must be exactly 160 px")
	var polygon := Layout.input_polygon(1280.0, "inspect", 274.0)
	assert(polygon.size() == 6, "overlay and shelf must use a concave L hit outline")
	assert(polygon == PackedVector2Array([
		inspect.position, Vector2(inspect.end.x, inspect.position.y), Vector2(control.end.x, control.end.y),
		Vector2(control.position.x, control.end.y), control.position, Vector2(inspect.position.x, strip_top),
	]))
	var debug := Layout.overlay_rect(1280.0, "debug")
	var debug_control := Layout.control_rect(1280.0, "debug", 350.0)
	assert(debug.end.y == Layout.strip_top("debug"))
	assert(debug_control.position.y >= Layout.strip_top("debug"))
	assert(Layout.input_polygon(1280.0, "debug", 350.0).size() == 6)
	print("Desktop layout tests passed")
	quit(0)
